name: Windows only test build
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: true
        update: true
        install: git make mercurial subversion

    - run: pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-SDL2
      if: ${{ (matrix.msystem == 'MINGW64') }}
    - run: pacman --noconfirm -S mingw-w64-i686-toolchain mingw-w64-i686-SDL2
      if: ${{ (matrix.msystem == 'MINGW32') }}

    - run: git fetch --prune --unshallow
    - run: gcc -v
    - run: "make STATIC=1 TARGET_NAME=dome CC=gcc"
    - uses: actions/upload-artifact@v3
      if: ${{ (matrix.msystem == 'MINGW32') }}
      with:
        name: dome-windows-x32
        path: |
          dome.exe
    - uses: actions/upload-artifact@v3
      if: ${{ (matrix.msystem == 'MINGW64') }}
      with:
        name: dome-windows-x64
        path: |
          dome.exe
